version: "3"

vars:
  PY: .venv/bin/python
  PIP: .venv/bin/pip

includes:
  env: tasks/env.yml
  pipeline: tasks/pipeline.yml

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list